[package]
name = "waswm"
version = "0.0.1"
authors = ["Mikhail Pogretskiy <mikhail.pogretskiy@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4"
env_logger = "0.9"
wasmer = "2.0"
x11rb = "0.8.1"
